name: Build

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # package:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: "write"
  #     contents: "read"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: DeterminateSystems/nix-installer-action@main
  #     - uses: DeterminateSystems/flake-checker-action@main
  #     - run: nix build
  #       working-directory: ./package
  #     - run: ./result/bin/yek
  #       working-directory: ./package

  zig:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake show
        working-directory: ./zig-app
      - run: nix build
        working-directory: ./zig-app
      - run: ./result/bin/zig-app
        working-directory: ./zig-app
